---
title: "Učíme online: rok podpory škol"
---

```{r setup, include=FALSE}
source(here::here("_packages.R"))
source(here::here("R/utils.R"))
knitr::opts_chunk$set(echo = FALSE, warning = FALSE, message = FALSE)

Sys.setlocale(locale = "cs_CZ.UTF-8", category = "LC_ALL")

options(scipen = 100)

ptrr::set_geom_defaults()
ptrr::set_ptrr_ggplot_fonts("Roboto Condensed")

targets::tar_load(mdf)
targets::tar_load(mdff)
targets::tar_load(g_poly_kraje)
targets::tar_load(g_poly_okresy)
targets::tar_load(mdf_with_at_mark)
targets::tar_load(mdf_with_at_mark_flat)
targets::tar_load(at_with_mdf_flat)
```

## Které školy si řekly o pomoc {.tabset}

100 % = všechny školy v dané kategorii
<span style='color: blue'>**modrý sloupec**</span>: podíl škol, kreré se přihlásily o podporu Učíme online

### Kapacita škol

```{r prihlasene-procento-kapacita, fig.height=2.5}
mdf_with_at_mark_flat %>% 
  filter(skola_druh_kod %in% c("B00", "C00")) %>% 
  mutate(skola_typ = fct_recode(skola_druh_kod, 
                                `Střední školy` = "C00", 
                                `Základní školy` = "B00")) %>% 
  group_by(kapacita_kat, skola_typ) %>% 
  summarise(help_requested = mean(help_requested, na.rm = T)) %>% 
  ggplot(aes(x = help_requested, y = kapacita_kat)) +
  geom_col() +
  theme_uo("x", multiplot = T, legend.position = "bottom") +
  scale_x_percent_cz(expand = flush_axis) +
  facet_wrap(~ skola_typ)
```

### Velikost obce

```{r prihlasene-procento-velikobce, fig.height=2.5}
mdf_with_at_mark_flat %>% 
  drop_na(obec_pocobyv_kat) %>% 
  filter(skola_druh_kod %in% c("B00", "C00")) %>% 
  mutate(skola_typ = fct_recode(skola_druh_kod, 
                                `Střední školy` = "C00", 
                                `Základní školy` = "B00")) %>% 
  group_by(obec_pocobyv_kat, skola_typ) %>% 
  summarise(help_requested = mean(help_requested, na.rm = T)) %>% 
  ggplot(aes(x = help_requested, y = obec_pocobyv_kat)) +
  geom_col() +
  theme_uo("x", multiplot = T, legend.position = "bottom") +
  scale_x_percent_cz(expand = flush_axis) +
  facet_wrap(~ skola_typ)
```


### Okres

```{r prihlasene-procento-okres, fig.height=3}
mdf_with_at_mark_flat %>% 
  replace_na(list(help_requested = FALSE)) %>% 
  filter(skola_druh_kod %in% c("B00", "C00")) %>% 
  mutate(skola_typ = fct_recode(skola_druh_kod, 
                                `Střední školy` = "C00", 
                                `Základní školy` = "B00")) %>% 
  group_by(okres_kod, skola_typ) %>% 
  summarise(help_requested = mean(help_requested, na.rm = T)) %>% 
  left_join(g_poly_okresy) %>% 
  st_as_sf() %>% 
  ggplot(aes(fill = help_requested)) +
  geom_sf(colour = "grey80") +
  scale_fill_viridis_b(labels = label_percent_cz(1),
                       name = "Podíl škol v okrese") +
  theme_uo(map = T, multiplot = T, legend.position = "bottom",
             legend.key.width = unit(1, "cm"), 
             legend.key.height = unit(.3, "cm")) +
  facet_wrap(~ skola_typ)

```

### Priorita ČŠI

```{r prihlasene-procento-prioritacsi, fig.height=2.5}
mdf_with_at_mark_flat %>% 
  filter(skola_druh_kod %in% c("B00", "C00")) %>% 
  mutate(skola_typ = fct_recode(skola_druh_kod, 
                                `Střední školy` = "C00", 
                                `Základní školy` = "B00")) %>% 
  mutate(csi_priorita = fct_explicit_na(csi_priorita,
                                        "Není na seznamu\nprioritních škol") %>% 
           fct_relevel("Není na seznamu\nprioritních škol", after = 0L)) %>% 
  group_by(csi_priorita, skola_typ) %>% 
  summarise(help_requested = mean(help_requested, na.rm = T)) %>% 
  ggplot(aes(y = csi_priorita, x = help_requested)) +
  geom_col() +
  facet_wrap(~skola_typ) +
  scale_x_percent_cz(expand = flush_axis) +
  labs(title = "Podíl") +
  theme_uo("x", multiplot = T)

```

### Používané technologie

```{r prihlasene-procento-technologie, fig.height=2}
mdf_with_at_mark_flat %>% 
  filter(skola_druh_kod %in% c("B00", "C00")) %>% 
  mutate(skola_typ = fct_recode(skola_druh_kod, 
                                `Střední školy` = "C00", 
                                `Základní školy` = "B00")) %>% 
  mutate(google_or_ms = if_else(dns_gsuite | dns_o365,
                                "Google/Microsoft",
                                "Jiná") %>% 
           fct_rev()) %>% 
  drop_na(google_or_ms) %>% 
  group_by(skola_typ, google_or_ms) %>% 
  summarise(help_requested = mean(help_requested, na.rm = T)) %>% 
  ggplot(aes(y = google_or_ms, x = help_requested)) +
  geom_col() +
  facet_wrap(~skola_typ) +
  scale_x_percent_cz(expand = flush_axis) +
  theme_uo("x", multiplot = T)
```

## Poptávky v čase {.tabset}

### Podle stupně

```{r poptavky-mesice-stupen, fig.height=2.5}
at_with_mdf_flat %>% 
  mutate(ym = floor_date(timestamp, "month"),
         stupen = fct_rev(stupen)) %>% 
  group_by(ym, stupen) %>% 
  count() %>% 
  ggplot(aes(ym, n, fill = stupen)) +
  geom_col() +
  scale_fill_brewer() +
  scale_x_datetime(labels = label_date_short(), date_breaks = "1 month", 
                   expand = expansion(add = c(24*3600*14, 24*3600*14))) +
  theme_uo("y")
```

### Podle priority ČŠI

```{r poptavky-mesice-prioritacsi-make}
gg_at_podil_csi <- at_with_mdf_flat %>% 
  mutate(ym = floor_date(timestamp, "month"),
         stupen = fct_rev(stupen)) %>% 
  mutate(skola_typ = fct_recode(skola_druh_kod, 
                                `Střední školy` = "C00", 
                                `Základní školy` = "B00") %>% 
           fct_other(c("Střední školy", "Základní školy"), 
                     other_level = "Ostatní") %>% 
           fct_explicit_na("Ostatní")) %>% 
  mutate(csi_priorita = fct_explicit_na(csi_priorita,
                                        "Není na seznamu\nprioritních škol") %>% 
           fct_relevel("Není na seznamu\nprioritních škol", after = 0L)) %>% 
  group_by(ym, csi_priorita, skola_typ) %>% 
  count() %>% 
  ggplot(aes(ym, n, fill = csi_priorita)) +
  geom_col() +
  scale_fill_brewer(palette = "YlOrBr") +
  scale_x_datetime(labels = label_date_short(), date_breaks = "1 month", 
                   expand = expansion(add = c(24*3600*14, 24*3600*14))) +
  theme_uo("y", multiplot = T) +
  facet_wrap(skola_typ~., nrow = 3) + 
  labs(fill = "Priorita dle ČŠI")
```

```{r poptavky-mesice-prioritacsi, fig.height=3}
gg_at_podil_csi
```

## Technologická mapa {.tabset}

### Podle velikosti obce

```{r techmapa-velobce-make}
tm_obec_pocobyv <- mdf_with_at_mark_flat %>% 
  group_by(obec_pocobyv_kat, skola_druh_nazev) %>% 
  filter(skola_druh_nazev %in% c("Střední škola", "Základní škola")) %>% 
  summarise(csi = mean(has_tech_selected, na.rm = T),
            google_or_ms = mean(dns_gsuite | dns_o365,
                                na.rm = TRUE),
            cnt = n()) %>% 
  drop_na(obec_pocobyv_kat) %>% 
  ggplot(aes(x = google_or_ms, y = obec_pocobyv_kat)) +
  scale_x_percent_cz(expand = flush_axis) +
  facet_wrap(~ fct_rev(skola_druh_nazev)) +
  theme_uo("x", multiplot = T) +
  geom_col() +
  labs(title = "Technologie Google/Microsoft podle velikosti obce",
       subtitle = "Podíl škol v dané kategorii, který měl buď Google nebo MS")
```

```{r techmapa-velobce, fig.height=2.5}
tm_obec_pocobyv
```


### Podle okresu

```{r techmapa-okres-make}
tm_okres <- crossing(skola_druh_nazev = unique(mdf_with_at_mark_flat$skola_druh_nazev),
                     okres_kod = unique(g_poly_okresy$okres_kod)) %>%  
  left_join(mdff %>% 
              mutate(okres_kod = if_else(str_detect(okres_kod, "CZ010"),
                                         "CZ0100", okres_kod)) %>% 
              filter(skola_druh_kod %in% c("B00", "C00")) %>% 
              group_by(okres_kod, skola_druh_nazev, skola_druh_kod) %>% 
              summarise(google_or_ms = mean(dns_gsuite | dns_o365,
                                            na.rm = TRUE)) 
  ) %>% 
  filter(skola_druh_kod %in% c("B00", "C00")) %>% 
  mutate(skola_typ = fct_recode(skola_druh_kod, 
                                `Střední školy` = "C00", 
                                `Základní školy` = "B00")) %>% 
  full_join(g_poly_okresy) %>% 
  st_as_sf() %>% 
  ggplot(aes(fill = google_or_ms)) +
  geom_sf(colour = "grey80") +
  scale_fill_viridis_b(labels = label_percent_cz(),
                       name = "Podíl škol v okrese") +
  theme_uo(map = T, multiplot = T, legend.position = "bottom",
             legend.key.width = unit(1, "cm"), 
             legend.key.height = unit(.3, "cm")) +
  facet_wrap(~ skola_typ) +
  labs(title = "Využití Google/Microsoft ve školách podle okresů",
       subtitle = "Školy s platformou Google nebo MS")

```

```{r techmapa-okres, fig.height=3.5}
tm_okres
```



